### PR TITLE
make pars work

### PR DESCRIPTION
**Pull request by martindurant**
This does suggest that handling user_parameters in intake leaves something to be desired.

There are two things:
- you need to include the user parameter names in the argument list for the entry. User parameters can also be used within string templates, so they don't necessarily refer to arguments to be passed to the data source
- the required type is string (is this always true?), so the dictionary of values to enable rich descriptions was being converted into a string like '[{"CODE": "full name"}, ...]', which obviously didn't even match the default string
- Intake doesn't handle an "other" type for the user parameters, but it should. For that case, coersion should be a no-op.

```python
import intake_sdmx
cat = intake_sdmx.SDMXSources()
cat2 = cat.NB
s = cat2.IR # all default values
s2 = s(UNIT_MEASURE='ANN') # override on argument
s2 = cat2.IR(UNIT_MEASURE='ANN') # same effect as line above
```

### CODE REVIEW

**Comment by martindurant** [comment]
(@dr-leo , ok so that made three points!)

**Comment by dr-leo** [comment]
Thanks. The templating does the trick. My latest commit builds on your work.

On "other type": Allowed values are currently of type dict to allow "rich descriptions". To make it work, I had subclassed UserParameter to provide a custom validation method thich uses only the dict key for validation. A more efficient alternative would be a tuple. And yes, one could also just concat code ID and description to something like "EXR:Exchange Rates", and have the validator match only the left part ("EXR", or, as you had suggested earlier, alternatively match against either part. 

However, as no coercion takes place, a dict or tuple seems to work as well, at least for param passing and validating. I cannot judge any other unwanted side efects.

Subject to any comment you may have on the above, I will next add a .read() method. Another TODO is passing around HTTP configs. But I guess this is for later (including whether we need an FSSPEC backend for SDMX or something).

So while I could easily add some code to query the specified data set and export it to pandas now, I wonder if there is a more elegant / best practice way of gleening the params other than accessing self.kwargs. I am asking as self.kwargs may contain all kinds of kwargs including any for which there are no UserParameters. OK, one can check the UserParameters to distinguish the corresponding kwargs from the rest. If that's best practice, I'll do just that.

On a separate note, when implementing UserParameters for startPeriod and endPeriod, I realized that besides the datetime type, there should be a Period type as in pandas. Any views? Happy to open an issue in the intake repo.

**Comment by martindurant** [comment]
> However, as no coercion takes place, a dict or tuple seems to work as well, at least for param passing and validating. I cannot judge any other unwanted side efects.

Coercion *is* taking place, which is why we need `self.allowed = allowed` to reset to the intended validation values. This works fine.

> Another TODO is passing around HTTP configs. But I guess this is for later (including whether we need an FSSPEC backend for SDMX or something).

Most drives that work on files of HTTP take a `storage_options` optional argument, which is passed to the fsspec backend. That should handle any auth, proxy, and timeout configurations. There is no reason you need fsspec here though, `requests` would do - since you always fetch a whole HTTP download every time; you don't need to worry about concurrent requests.

>  I wonder if there is a more elegant / best practice way of gleening the params other than accessing self.kwargs. 

This is exactly the most common pattern. 

> besides the datetime type, there should be a Period type as in pandas

Makes sense. The restriction is, that each type needs a string name to allow for a validator to be attached, because these user_parameter descriptions need to be serialisable in YAML (for catalogue files) and msgpack (for the server). The period value itself would be written as a string like "7d", right? It might be good to explicitly include an "other" type which does no coercion.

**Comment by dr-leo** [comment]
Two more questions that have arisen along the way:

1. args propagation in .reconfigure_new()

Creating a new instance from an existing one resets all args to their
default values (from UserParameters) unless explicitly provided to
overwrite them; maybe I am confusing args and params here.

I find this behavior somewhat counter-intuitive and would rather
expect that the new instance  will be populated from the existing
instance's args, unless overwritten by the caller. Is the observed
resetting behavior a bug of intake_sdmx or a feature of intake?

2. Storing full metadata in the DataSource instance or not?

To recap: The catalog of dataflows for a given SDMX data source (eg.
NB or ECB) uses a lazy dict to create entries on demand, because
creating an entry is expensive as a large XML file must be downloaded
and parsed. Now, the DataSource instance requires that same metadata
to produce a DataFrame from the acquired dataset. It would be easy to
store the raw XML as bytes (sometimes over 500k) in the metadata dict.
If we don't do that, the XML file would still be cached by the
underlying requests HTTP lib (by default in a SQLite DB). So the
performance gain of storing the XML in the DataSource instance would
be minimal. But storing the XML in the metadata would embed all
metadata in the distributable yaml file. the metadata is relatively
stable. Best practice? Trade-offs?

In this context: I think the SDMX DataSource class needs a .discover()
method anyway to download the XML metadata. Or is it ok to do this in
.read()? Note that such .discover() method would only be called if we
decided against storing the XML in the metadata dict, or if the
DataSource instance were created from scratch rather than from the
catalog.

3. UserParameter: select multiple allowed values

I haven't tested this. But my impression is that this is not possible.
I think it should. And it would be easy to add this feature to
UserParameter without breaking any code. Just add a new parameter,
say: `allow_multiple`(bool). If True, an iterable of type would pass
validation if all items are in self.allowed. That's it. I could do a
PR for intake if you agree.

5. Next steps

- finish work on dataframe export
- add a search method to the dataflows cat. I hope to get some
inspiration from the base class. Otherwise, I might provide a function
for .filter(). I now tend to keep it simple and build the catalog from
both names and descriptions, so there would be an entry named "ECB"
and another "European Central Bank". I don't quite like this, but I do
not see any good alternative.

**Comment by martindurant** [comment]
> Is the observed resetting behavior a bug of intake_sdmx or a feature of intake?

This is a bug, I will fix it. I'll push this and get back to you on the other questions shortly.

**Comment by martindurant** [comment]
> he SDMX DataSource class needs a .discover()
method anyway to download the XML metadata. Or is it ok to do this in
.read()?

It is fairly normal to have read() call discover() (or some mutually shared method such as _load_metadata) and store the results in an instance method.

Am I correctly understanding that the metadata XML is required at *entry* creation time (to decide what parameters are allowed, for instance)? Then, I would keep that result in that entry, and have the lazy dict keep the entry around - perhaps a LRU cache with some reasonable or configurable number of entries. I'm not principally opposed to writing it into a YAML representation, but you would loose the human-readable quality of YAML. Also, you could, in principle, end up duplicating the metadata many times, if a catalogue is to have several instances of a given data product, differing only in parameter selection.

> UserParameter: select multiple allowed values

Indeed you are right, this is not currently possible. Rather than add a new option, I would make a new type. There could be many of these, but "list" and "dict" would be obvious candidates, as well as the "other" that you initially tried (this latter would have no validation, or perhaps we provide an argument to user_parameter whereby the catalogue author can specify a validation method). For a type like "list", which is what you want here, it would be an open question whether to do validation beyond the `type()` of the passed argument, e.g., whether the elements are of a given type or whether elements can repeat. I feel like python type hints might be the natural way to do all of this.

> I might provide a function for .filter().

I would prefer to keep the name "search", which is meant to be overloadable, and adapted to each catalogue type that needs more than a simple text search.

> there would be an entry named "ECB"
and another "European Central Bank". I don't quite like this, but I do
not see any good alternative.

There is always something clever you can do, but it might well not be worth it. For example, you could have both "ECB" and "European Central Bank" generate the same entry in your dictionary's __get_item__, but not only list one set by overloading keys() and __iter__().

Here is a non-lazy example dict that only lists every second key, but you can still get those keys and check for inclusion. The non-listed keys do not show up for tab-completion in ipython.
```
In [10]: class notdict(dict):
    ...:     def keys(self):
    ...:         return list(dict.keys(self))[::2]
    ...:     def __iter__(self):
    ...:         return iter(self.keys())
    ...:

In [11]: nd = notdict(oi=1, bah=2, frub=3)

In [12]: list(nd)
Out[12]: ['oi', 'frub']

In [15]: nd['bah']
Out[15]: 2

In [16]: 'bah' in nd
Out[16]: True

In [18]: list(nd.items()) # might have wanted to also override items() and/or values()
Out[18]: [('oi', 1), ('bah', 2), ('frub', 3)]
```

**Comment by dr-leo** [comment]
Great! - Please open a new PR for that fix if it is to be made in
intake_sdmx. Since merging this PR I have done some more work.
Exporting to pandas DataFrame is largely complete.

**Comment by martindurant** [comment]
The fix is in https://github.com/intake/intake/pull/598 ; it's not very elegant as it stands, and I hope one of my colleagues comes up with something neater before I merge it.

**Pull request merged**
